version: '3.7'

services:
  reverse-proxy:
    image: traefik:1.7.9
    command: --configfile='/container/traefik.toml'
    healthcheck:
      test: [CMD, /traefik, healthcheck, --configfile=/container/traefik.toml]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 15s
    networks:
      global_reverse-proxy:
        aliases:
          - reverse-proxy
          - reverse-proxy.docker
          - reverse-proxy.global.docker
      user1_reverse-proxy:
        aliases:
          - reverse-proxy
          - reverse-proxy.docker
          - reverse-proxy.global.docker
      user2_reverse-proxy:
        aliases:
          - reverse-proxy
          - reverse-proxy.docker
          - reverse-proxy.global.docker
    expose:
      # traefik dashboard
      - '8000'
    ports:
      # Ports must be exposed in 'host' mode instead of 'ingress', otherwise the
      # incoming requests IP will be lost. For more information see:
      # https://github.com/moby/moby/issues/25526
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/global/reverse-proxy:/container
    deploy:
      labels:
        - bindMountOwner=0:0
      placement:
        constraints: [node.role == manager]
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        reservations:
          memory: 60M
        limits:
          memory: 400MB

  error-pages:
    image: nginx:1.15-alpine
    command: nginx -g 'daemon off;' -c /container/nginx.conf
    networks:
      global_reverse-proxy:
        aliases:
          - error-pages.global.docker
    expose:
      - '8080'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/global/reverse-proxy/error-pages:/container
    deploy:
      labels:
        - bindMountOwner=100:101
        - bindMountMode=0770
        - updateService=true
        - traefik.enable=true
        - traefik.docker.network=global_reverse-proxy
        - 'traefik.frontend.rule=HostRegexp:{catchall:.*};ReplacePath: /raise-503-error'
        - traefik.frontend.priority=1
        - traefik.port=8080
        - traefik.weight=10
        - traefik.backend=error
        - traefik.backend.loadbalancer.method=drr
        - traefik.backend.loadbalancer.stickiness=false
        - traefik.backend.loadbalancer.swarm=true
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      resources:
        limits:
          cpus: '0.1'
          memory: 20MB
      update_config:
        parallelism: 1
        delay: 10s

networks:
  global_reverse-proxy:
    name: global_reverse-proxy
    driver: overlay
    attachable: true
    # use explicit subnet
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
  user1_reverse-proxy:
    name: user1_reverse-proxy
    driver: overlay
    attachable: true
  user2_reverse-proxy:
    name: user2_reverse-proxy
    driver: overlay
    attachable: true
