version: '3.7'

services:
  redis:
    image: aisberg/redis:4.0.11
    environment:
      - REDIS_DATABASES=3
      - REDIS_REQUIREPASS=lnFl4MzarOL5bTEbreld
      - REDIS_MAXCLIENTS=500
      - REDIS_MAXMEMORY=300mb
    networks:
      redis:
        aliases:
          - redis
          - redis.org1.docker
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/org1/redis/redis:/container/redis
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      resources:
        limits:
          cpus: '2.0'
          memory: 300mb
      update_config:
        parallelism: 1
        delay: 10s

networks:
  redis:
    name: org1_redis
    driver: overlay
    attachable: true

